pull_request_rules:
  - name: Automatic merge on CI and reviews
    conditions:
      - status-success=continuous-integration/travis-ci/push
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch:
