pull_request_rules:
  - name: Automatic merge on CI and reviews
    conditions:
      - status-success=Travis CI - Branch
      - '#approved-reviews-by>=1'
      - '#change-requested-reviews-by=0'
    actions:
      merge:
        method: merge
      delete_head_branch:
