pull_request_rules:
  - name: Automatic merge on CI and reviews
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - '#approved-reviews-by>=1'
    actions:
      merge:
        method: merge
        delete_head_branch:
