language: node_js
node_js:
  - node # uses most recent stable node version
cache: npm # cache installed npm packages for faster build times.
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "real-fake-spaceshop-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: real-fake-spaceshop
  api_key:
    secure: JtB9+iW5//uuYCzAYihXP29+qgvnkx7XD6GGH6t1gqre8SHVvcfK2kG9lkHUEVHrDhuJnoR30RCy5B/QRVQOVc7m5hGEDQSFItidQ5k+HhRDsFZEkf1z+RADAzfBkJJsxLD7EEIWKPh0X/Esyi+uLzHzm9fl/yEcJiSbptwUKfmHBAglgPC48tfbha4F0AIZZNNFq+FyG/tWd2P52+TBdcHgfUQET472L9tSzuSKdkkaqVpBWmbmma2JyZMA6MO9F2XGFbSrBRY2k5V23z9o6E5DWIPAPh++GpQBoMpGyzfNeZFCu/winLJLd9ZiEi3HJNEFnIH9VHYsuilbCaKWLjj5FMKl59WZ6NioybXHB+UsiE3g8rGNFxZ/K4a3nIQoAAeG0zPFCTvlpJSd+tOXVJNbV6PkQmdb0Hp7R1zYu+ru7Y81Lk/u4zmgOS8e3bRs8JJknB+1kx47ypPYuCliTBGDQ+i9SPI+zq2FUDAFPXMql5aZI/2Tkofy8kZLYQUmCAkNpnmtDpx6qZchZt7eoCinHjCwbsrbn3G5xGA53tnlm7mtb3t8ijMDmjOr9wbxNzKt3Sgf/PBdsSMq55qRV9EOSrHs1879uQj5cq/nzkMnMasiGZMEbOl36C/5iMLlS7oVcilZKRh/I4+0cQGAlQVz7VoO0L3/S5M+0an9kgE=
